spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/board?autoReconnect=true
    username: root
    password: 1234


mybatis:
  type-aliases-package: com.example.frontendbackenddatabasepractice.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml


